channels:
  - conda-forge
  - default
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - joblib
  - scikit-learn-intelex
  - salib
  - sixs
  - Py6S
  - pip
  pip:
    - git+https://github.com/hectornieto/pyTSEB
